In [1]:
import numpy as np

## arange function 

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## sqrt function 

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

## ??


In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([-0.28122256,  0.63832209,  1.5422276 , -0.04626495, -0.50291216,
        0.55029852, -0.07913712, -1.30871577, -0.47955156,  1.93867872])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([-0.5311092 , -1.61397147,  1.36924236, -0.92186173, -0.39080648,
       -0.55543516, -0.21144108, -0.59532664,  1.58364351,  1.31966629])

In [12]:
#Binary Function
np.add(A,B)

array([-0.81233177, -0.97564938,  2.91146995, -0.96812668, -0.89371864,
       -0.00513664, -0.29057821, -1.90404241,  1.10409195,  3.25834501])

In [13]:
np.maximum(A,B)

array([-0.28122256,  0.63832209,  1.5422276 , -0.04626495, -0.39080648,
        0.55029852, -0.07913712, -0.59532664,  1.58364351,  1.93867872])