## Arrays and Scalars 

In [9]:
import numpy as np

In [10]:
5/2

2.5

In [11]:
5.0/2

2.5

## import division function 

In [12]:
from __future__ import division

In [13]:
5/2

2.5

In [15]:
arr1 = np.array([[1,2,3,4],[10,11,12,13]])

In [16]:
arr1

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [17]:
arr1*arr1

array([[  1,   4,   9,  16],
       [100, 121, 144, 169]])

In [18]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.1       ,  0.09090909,  0.08333333,  0.07692308]])